# docker compose service
services:
  meshsight-gateway:
    build:
      context: ./meshsight-gateway
      dockerfile: Dockerfile
    image: meshsight-gateway-api:0.0.1
    container_name: meshsight-gateway
    restart: unless-stopped
    ports:
      - "8331:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/meshsight-gateway:/tmp
      - ./data/meshsight-gateway/configs:/workspace/configs
    depends_on:
      - meshsight-gateway-postgres
    networks:
      - meshsight-network
  meshsight-gateway-postgres:
    image: postgres:16
    container_name: meshsight-gateway-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=1000'
      - '-c'
      - 'idle_in_transaction_session_timeout=30s'
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/meshsight-gateway-postgres/data:/var/lib/postgresql/data
    networks:
      - meshsight-network
# docker compose network
networks:
  meshsight-network:
    name: meshsight-network
    external: true
