timezone: "Asia/Taipei"

cache:
  path: "/tmp/meshsight-gateway"
  ttl: 3600

mqtt:
  host: "mqtt.meshtastic.org"
  port: 1883
  identifier: "MeshSight-Gateway"
  username: "meshdev"
  password: "large4cats"
  topics: [
      # https://meshtastic.org/docs/configuration/radio/lora/#region
      "msh/US/#",
      "msh/EU_433/#",
      "msh/EU_868/#",
      "msh/CN/#",
      "msh/JP/#",
      "msh/ANZ/#",
      "msh/KR/#",
      "msh/TW/#",
      "msh/RU/#",
      "msh/IN/#",
      "msh/NZ_865/#",
      "msh/TH/#",
      "msh/UA_433/#",
      "msh/UA_868/#",
      "msh/MY_433/#",
      "msh/MY_919/#",
      "msh/SG_923/#",
      "msh/LORA_24/#",
      # custom
      "msh/custom/#"
    ]

meshtastic:
  channels:
    - name: "LongFast"
      key: "1PG7OiApB1nwvP+rz05pAQ==" # aka AQ==
  position:
    expire: 40 # 定位資料保留天數，單位為 hour
    maxQueryPeriod: 36 # 最大查詢期限，單位為 hour

postgres:
  host: "MeshSight-Gateway-PostgreSQL"
  port: "5432"
  database: "postgres"
  username: "postgres"
  password: "changeme"
